import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Link from 'next/link'
import styles from './layout.module.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        cz-shortcut-listen="true"
      >
        <nav className={styles.navigation}>
          <Link href="/" className={styles.navLink}>
            Main
          </Link>
          <Link href="/react-final-form" className={styles.navLink}>
            React Final Form
          </Link>
          <Link href="/react-hook-form" className={styles.navLink}>
            React Hook Form
          </Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
